### ISSUE TITLE
Convert WA-Tracker to a backend

### ISSUE THREAD

**Issue by Rexota** [mgp25/WA-Tracker#16]
Hello

I've been messing with WA-Tracker, it's great tool. I thank you for it. 

I want to convert this to a script to follow more people from a database, as a back-end for my C# program.

What would you do ? I'm searching for the most efficient way.

**Comment by mgp25** [comment]
I dont recommend it, your number will be blocked if you try massive requests

Regards

**Comment by Rexota** [comment]
Thanks for your advice. What do you mean by "massive" ?

**Comment by mgp25** [comment]
multiple/bulk requests

**Comment by Rexota** [comment]
Thank you.

**Comment by Rexota** [comment]
Is it possible to use as back-end? Because WhatsApp allows only one connection per phone number.

I saw a few android apps that does tracking (paid), I doubt they are working correct, but if they are working correct, how are they doing this?
