### ISSUE TITLE
Not receiving presence

### ISSUE THREAD

**Issue by ghacproductions** [mgp25/WA-Tracker#8]
Hello,

I just tested out the newest version of the wa-tracker, everything works fine, expect the "cHidden"/"cRemote1"-mode with user's online state. I'm not receiving incoming presence updates. Some ideas to fix this problem?

Thanks,
ghac

**Comment by mgp25** [comment]
@ghacproductions set debug to true and post debug log

Regards

**Comment by ghacproductions** [comment]
I think, I've got the reason, as there is no onPresence-event at the moment, it seems like it's now splitted up in two events, onPresenceAvailable and onPresenceUnavailable.

This would explain, why the event is never fired.

**Comment by mgp25** [comment]
Ill update script later.

Thanks

**Comment by mgp25** [comment]
@ghacproductions check now :) see latest commit, tell me if everything works now

Regards

**Comment by mgp25** [comment]
Fixed.
