### ISSUE TITLE
'Connection Closed' exception is shown for every continuous monitoring

### ISSUE THREAD

**Issue by shimonelbaz** [mgp25/WA-Tracker#9]
whenever trying to use continuous monitoring like -check or cHidden , you get a connection closed after a few seconds.
![check](https://cloud.githubusercontent.com/assets/12231912/7451537/78968e5c-f25a-11e4-9465-6aeb32eb22ef.png)
![chidden](https://cloud.githubusercontent.com/assets/12231912/7451538/78970f58-f25a-11e4-9dcc-7ca5e8f23dae.png)

**Comment by mgp25** [comment]
@shimonelbaz set debug to true, and post debug output

**Comment by shimonelbaz** [comment]
in which file?
cause when i did it in the file "whatsprot.class.php" and it looks the same

Thanks,
Shimon.

**Comment by mgp25** [comment]
`watracker.php`

**Comment by mgp25** [comment]
@shimonelbaz 
```php
$wa = new WhatsProt($sender, 'WhatsApp Tracker', FALSE);
```

Change `FALSE` to `TRUE`

**Comment by shimonelbaz** [comment]
** change file extension to ZIP



![logs](https://cloud.githubusercontent.com/assets/12231912/7452652/033dcf4e-f269-11e4-96ae-4bef67fcaf99.png)

**Comment by mgp25** [comment]
@shimonelbaz no, dont change extension, just change the line i told you.

**Comment by shimonelbaz** [comment]
changed , but i cannot attach log files or zips. so i zipped them and
attached with a different extension.

**Comment by mgp25** [comment]
@shimonelbaz just copy and paste the output here once you run it

**Comment by shimonelbaz** [comment]
for check function:

====================================================
               WhatsApp tracker v0.1                
====================================================

[*] Logging in as WhatsApp Tracker (972523714226)
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="972523714226">‎׳7972523714226S״תrמּױ @ן¬ׂ74y|®¡1430738365</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>׳¼W	ל
,1 VNא¼</challenge>

tx  <response>÷„‰(םFֵ|4,ךי¸,„ה+¥µ-M`₪¦{²*j</response>

rx  <success t="1430738365" props="4" kind="free" status="active" creation="1430309638" expiration="1461845638">`¯J‚Rv_n`™כT-‹*></success>

tx  <presence name="WhatsApp Tracker"></presence>


[-] Tracker mode (ON):
tx  <iq to="972528037196@s.whatsapp.net" type="get" id="1430738365-1" xmlns="jabber:iq:last">
tx    <query></query>
tx  </iq>

rx  <receipt from="972528037196@s.whatsapp.net" id="1430714226-4" offline="0" t="1430714290"></receipt>

tx  <ack to="972528037196@s.whatsapp.net" id="1430714226-4" type="read" t="1430738365"></ack>

rx  <receipt from="972528037196@s.whatsapp.net" id="1430714299-2" offline="0" t="1430714300"></receipt>

tx  <ack to="972528037196@s.whatsapp.net" id="1430714299-2" type="read" t="1430738365"></ack>

rx  <receipt from="972528037196@s.whatsapp.net" id="1430714299-2" offline="0" type="read" t="1430714307">
rx    <list>
rx      <item id="1430714226-4"></item>
rx    </list>
rx  </receipt>

tx  <ack to="972528037196@s.whatsapp.net" id="1430714299-2" type="read" t="1430738365"></ack>

rx  <receipt from="972528037196@s.whatsapp.net" id="1430714387-2" offline="0" t="1430714390"></receipt>

tx  <ack to="972528037196@s.whatsapp.net" id="1430714387-2" type="read" t="1430738365"></ack>

rx  <receipt from="972528037196@s.whatsapp.net" id="1430714387-2" offline="0" type="read" t="1430714436"></receipt>

tx  <ack to="972528037196@s.whatsapp.net" id="1430714387-2" type="read" t="1430738365"></ack>

rx  <receipt from="972528037196@s.whatsapp.net" id="1430714511-2" offline="0" t="1430714512"></receipt>

tx  <ack to="972528037196@s.whatsapp.net" id="1430714511-2" type="read" t="1430738365"></ack>

rx  <receipt from="972528037196@s.whatsapp.net" id="1430714532-2" offline="0" t="1430714532"></receipt>

tx  <ack to="972528037196@s.whatsapp.net" id="1430714532-2" type="read" t="1430738365"></ack>

rx  <receipt from="972528037196@s.whatsapp.net" id="1430714740-2" offline="0" t="1430714743"></receipt>

tx  <ack to="972528037196@s.whatsapp.net" id="1430714740-2" type="read" t="1430738365"></ack>

rx  <receipt from="972528037196@s.whatsapp.net" id="1430714857-2" offline="0" t="1430714860"></receipt>

tx  <ack to="972528037196@s.whatsapp.net" id="1430714857-2" type="read" t="1430738365"></ack>

rx  <receipt from="972528037196@s.whatsapp.net" id="1430714857-2" offline="0" type="read" t="1430714862">
rx    <list>
rx      <item id="1430714740-2"></item>
rx      <item id="1430714532-2"></item>
rx      <item id="1430714511-2"></item>
rx    </list>
rx  </receipt>

tx  <ack to="972528037196@s.whatsapp.net" id="1430714857-2" type="read" t="1430738365"></ack>

rx  <receipt from="972528037196@s.whatsapp.net" id="1430714979-2" offline="0" t="1430714989"></receipt>

tx  <ack to="972528037196@s.whatsapp.net" id="1430714979-2" type="read" t="1430738365"></ack>

rx  <receipt from="972528037196@s.whatsapp.net" id="1430714979-2" offline="0" type="read" t="1430715012"></receipt>

tx  <ack to="972528037196@s.whatsapp.net" id="1430714979-2" type="read" t="1430738365"></ack>

rx  <receipt from="972506361136@s.whatsapp.net" id="1430715241-2" offline="0" t="1430715261"></receipt>

tx  <ack to="972506361136@s.whatsapp.net" id="1430715241-2" type="read" t="1430738365"></ack>

rx  <receipt from="972506361136@s.whatsapp.net" id="1430715241-2" offline="0" type="read" t="1430715263"></receipt>

tx  <ack to="972506361136@s.whatsapp.net" id="1430715241-2" type="read" t="1430738365"></ack>

rx  <receipt from="972528037196@s.whatsapp.net" id="1430715338-1" offline="0" t="1430715341"></receipt>

tx  <ack to="972528037196@s.whatsapp.net" id="1430715338-1" type="read" t="1430738365"></ack>

rx  <receipt from="972528037196@s.whatsapp.net" id="1430715338-1" offline="0" type="read" t="1430715367"></receipt>

tx  <ack to="972528037196@s.whatsapp.net" id="1430715338-1" type="read" t="1430738365"></ack>

rx  <receipt from="972528037196@s.whatsapp.net" id="1430715551-1" offline="0" t="1430715557"></receipt>

tx  <ack to="972528037196@s.whatsapp.net" id="1430715551-1" type="read" t="1430738365"></ack>

rx  <receipt from="972528037196@s.whatsapp.net" id="1430715601-1" offline="0" t="1430715608"></receipt>

tx  <ack to="972528037196@s.whatsapp.net" id="1430715601-1" type="read" t="1430738365"></ack>

rx  <receipt from="972528037196@s.whatsapp.net" id="1430715601-1" offline="0" type="read" t="1430715839">
rx    <list>
rx      <item id="1430715551-1"></item>
rx    </list>
rx  </receipt>

tx  <ack to="972528037196@s.whatsapp.net" id="1430715601-1" type="read" t="1430738365"></ack>

rx  <receipt from="972528037196@s.whatsapp.net" id="1430718041-1" offline="0" t="1430718044"></receipt>

tx  <ack to="972528037196@s.whatsapp.net" id="1430718041-1" type="read" t="1430738365"></ack>

rx  <receipt from="972528037196@s.whatsapp.net" id="1430718075-1" offline="0" t="1430718078"></receipt>

tx  <ack to="972528037196@s.whatsapp.net" id="1430718075-1" type="read" t="1430738365"></ack>

rx  <receipt from="972528037196@s.whatsapp.net" id="1430718104-1" offline="0" t="1430718107"></receipt>

tx  <ack to="972528037196@s.whatsapp.net" id="1430718104-1" type="read" t="1430738365"></ack>

rx  <receipt from="972528037196@s.whatsapp.net" id="1430718104-1" offline="0" type="read" t="1430718183">
rx    <list>
rx      <item id="1430718075-1"></item>
rx      <item id="1430718041-1"></item>
rx    </list>
rx  </receipt>

tx  <ack to="972528037196@s.whatsapp.net" id="1430718104-1" type="read" t="1430738365"></ack>

rx  <receipt from="972528037196@s.whatsapp.net" id="1430720675-1" offline="0" t="1430720677"></receipt>

tx  <ack to="972528037196@s.whatsapp.net" id="1430720675-1" type="read" t="1430738365"></ack>

rx  <receipt from="972528037196@s.whatsapp.net" id="1430720675-1" offline="0" type="read" t="1430720702"></receipt>

tx  <ack to="972528037196@s.whatsapp.net" id="1430720675-1" type="read" t="1430738365"></ack>

rx  <receipt from="972528037196@s.whatsapp.net" id="1430720713-1" offline="0" type="read" t="1430720714"></receipt>

tx  <ack to="972528037196@s.whatsapp.net" id="1430720713-1" type="read" t="1430738365"></ack>

rx  <receipt from="972528037196@s.whatsapp.net" id="1430720758-1" offline="0" t="1430720884"></receipt>

tx  <ack to="972528037196@s.whatsapp.net" id="1430720758-1" type="read" t="1430738365"></ack>

rx  <receipt from="972528037196@s.whatsapp.net" id="1430720758-1" offline="0" type="read" t="1430720885"></receipt>

tx  <ack to="972528037196@s.whatsapp.net" id="1430720758-1" type="read" t="1430738365"></ack>

rx  <receipt from="972528037196@s.whatsapp.net" id="1430720899-1" offline="0" t="1430720900"></receipt>

tx  <ack to="972528037196@s.whatsapp.net" id="1430720899-1" type="read" t="1430738365"></ack>

rx  <receipt from="972528037196@s.whatsapp.net" id="1430720911-1" offline="0" t="1430720929"></receipt>

tx  <ack to="972528037196@s.whatsapp.net" id="1430720911-1" type="read" t="1430738365"></ack>

rx  <receipt from="972528037196@s.whatsapp.net" id="1430720911-1" offline="0" type="read" t="1430720935">
rx    <list>
rx      <item id="1430720899-1"></item>
rx    </list>
rx  </receipt>

tx  <ack to="972528037196@s.whatsapp.net" id="1430720911-1" type="read" t="1430738365"></ack>

rx  <receipt from="972528037196@s.whatsapp.net" id="1430720957-1" offline="0" t="1430720993"></receipt>

tx  <ack to="972528037196@s.whatsapp.net" id="1430720957-1" type="read" t="1430738365"></ack>

rx  <receipt from="972528037196@s.whatsapp.net" id="1430721096-1" offline="0" t="1430721336"></receipt>

tx  <ack to="972528037196@s.whatsapp.net" id="1430721096-1" type="read" t="1430738365"></ack>

rx  <receipt from="972528037196@s.whatsapp.net" id="1430721131-1" offline="0" t="1430721336"></receipt>

tx  <ack to="972528037196@s.whatsapp.net" id="1430721131-1" type="read" t="1430738365"></ack>

rx  <receipt from="972528037196@s.whatsapp.net" id="1430721168-1" offline="0" t="1430721336"></receipt>

tx  <ack to="972528037196@s.whatsapp.net" id="1430721168-1" type="read" t="1430738365"></ack>

rx  <receipt from="972528037196@s.whatsapp.net" id="1430721168-1" offline="0" type="read" t="1430721337">
rx    <list>
rx      <item id="1430720957-1"></item>
rx      <item id="1430721096-1"></item>
rx      <item id="1430721131-1"></item>
rx    </list>
rx  </receipt>

tx  <ack to="972528037196@s.whatsapp.net" id="1430721168-1" type="read" t="1430738365"></ack>

rx  <receipt from="972528037196@s.whatsapp.net" id="1430721168-1" offline="0" type="read" t="1430721337">
rx    <list>
rx      <item id="1430720957-1"></item>
rx      <item id="1430721096-1"></item>
rx      <item id="1430721131-1"></item>
rx    </list>
rx  </receipt>

tx  <ack to="972528037196@s.whatsapp.net" id="1430721168-1" type="read" t="1430738365"></ack>

rx  <receipt from="972528037196@s.whatsapp.net" id="1430721236-1" offline="0" type="read" t="1430721337"></receipt>

tx  <ack to="972528037196@s.whatsapp.net" id="1430721236-1" type="read" t="1430738365"></ack>

rx  <receipt from="972529530096@s.whatsapp.net" id="1430721474-1" offline="0" t="1430721475"></receipt>

tx  <ack to="972529530096@s.whatsapp.net" id="1430721474-1" type="read" t="1430738365"></ack>

rx  <receipt from="972529530096@s.whatsapp.net" id="1430721474-1" offline="0" type="read" t="1430721482"></receipt>

tx  <ack to="972529530096@s.whatsapp.net" id="1430721474-1" type="read" t="1430738365"></ack>

rx  <receipt from="972528037196@s.whatsapp.net" id="1430721298-1" offline="0" t="1430721485"></receipt>

tx  <ack to="972528037196@s.whatsapp.net" id="1430721298-1" type="read" t="1430738365"></ack>

rx  <receipt from="972528037196@s.whatsapp.net" id="1430721298-1" offline="0" type="read" t="1430721487"></receipt>

tx  <ack to="972528037196@s.whatsapp.net" id="1430721298-1" type="read" t="1430738365"></ack>

rx  <receipt from="972528037196@s.whatsapp.net" id="1430729669-1" offline="0" t="1430729669"></receipt>

tx  <ack to="972528037196@s.whatsapp.net" id="1430729669-1" type="read" t="1430738365"></ack>

rx  <receipt from="972528037196@s.whatsapp.net" id="1430729669-1" offline="0" type="read" t="1430729681"></receipt>

tx  <ack to="972528037196@s.whatsapp.net" id="1430729669-1" type="read" t="1430738365"></ack>

rx  <receipt from="972528037196@s.whatsapp.net" id="1430729686-1" offline="0" type="read" t="1430729686"></receipt>

tx  <ack to="972528037196@s.whatsapp.net" id="1430729686-1" type="read" t="1430738365"></ack>

rx  <receipt from="972528037196@s.whatsapp.net" id="1430729777-1" offline="0" type="read" t="1430729779"></receipt>

tx  <ack to="972528037196@s.whatsapp.net" id="1430729777-1" type="read" t="1430738365"></ack>

rx  <ib from="s.whatsapp.net">
rx    <offline count="46"></offline>
rx  </ib>

rx  <presence from="972523714226@s.whatsapp.net"></presence>

rx  <iq from="972528037196@s.whatsapp.net" id="1430738365-1" type="result">
rx    <query seconds="493"></query>
rx  </iq>

- Last seen: 0 days 0 hours 8 minutes ago
tx  <iq to="972528037196@s.whatsapp.net" type="get" id="1430738365-2" xmlns="jabber:iq:last">
tx    <query></query>
tx  </iq>

rx  <stream:error>
rx    <conflict></conflict>
rx    <text>Replaced by new connection</text>
rx  </stream:error>

**Comment by shimonelbaz** [comment]
comes out as gibrish....

**Comment by mgp25** [comment]
@shimonelbaz you cant use your whatsapp in your device meanwhile using this script. WhatsApp only admits one session. Look at the stream error:

```xml
rx  <stream:error>
rx    <conflict></conflict>
rx    <text>Replaced by new connection</text>
rx  </stream:error>
```

**Comment by shimonelbaz** [comment]
happens with another whatsapp account when the device is turned off

**Comment by mgp25** [comment]
@shimonelbaz then someone is trying to connect at the same time to the same number, dont run multiple instances of this script with the same number

**Comment by shimonelbaz** [comment]
no one was trying to connect to this account.
it seems that sometimes the content of the folder "wadata" becomes corrupted and causes this issue.
deleting the files in the folder and running the script again fixes the issue.
